### ISSUE TITLE
TextDecoder is not defined

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/distributions#343]
This happens now (also with a checkout from scratch):

```
** Building site **
npm run build

> dist.ipfs.io@1.0.0 build /home/hector/ipn/distributions
> npm run dist && npm run build:assets && npm run build:hugo


> dist.ipfs.io@1.0.0 dist /home/hector/ipn/distributions
> node scripts/dist.js

/home/hector/ipn/distributions/node_modules/cids/node_modules/multibase/src/util.js:3
const textDecoder = new TextDecoder()
                    ^

ReferenceError: TextDecoder is not defined
    at Object.<anonymous> (/home/hector/ipn/distributions/node_modules/cids/node_modules/multibase/src/util.js:3:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/hector/ipn/distributions/node_modules/cids/node_modules/multibase/src/base.js:3:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dist.ipfs.io@1.0.0 dist: `node scripts/dist.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dist.ipfs.io@1.0.0 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hector/.npm/_logs/2021-05-03T16_31_24_090Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dist.ipfs.io@1.0.0 build: `npm run dist && npm run build:assets && npm run build:hugo`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dist.ipfs.io@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hector/.npm/_logs/2021-05-03T16_31_24_111Z-debug.log
make: *** [Makefile:20: site] Error 1
[18:31:24] ~/i/distributions (cluster-v0.13.
```

**Comment by hsanjuan** [comment]
Reverting 29005bbf12 fixes it.

**Comment by Stebalien** [comment]
Support for `TextDecoder` was added in Node v11 (released in 2019), the current LTS is 14.16.1, the current release is 16.1.0.

**Comment by hsanjuan** [comment]
Using nodejs 16.1.0:

```
> dist.ipfs.io@1.0.0 webpack:build
> webpack -p --display minimal

/home/hector/ipn/distributions/node_modules/webpack-cli/bin/cli.js:281
				throw err;
				^

Error: Cannot find module 'buffer-shims'
Require stack:
- /home/hector/ipn/distributions/node_modules/readable-stream/lib/_stream_readable.js
- /home/hector/ipn/distributions/node_modules/readable-stream/readable.js
- /home/hector/ipn/distributions/node_modules/duplexify/index.js
- /home/hector/ipn/distributions/node_modules/pumpify/index.js
- /home/hector/ipn/distributions/node_modules/mississippi/index.js
- /home/hector/ipn/distributions/node_modules/cacache/lib/entry-index.js
- /home/hector/ipn/distributions/node_modules/cacache/ls.js
- /home/hector/ipn/distributions/node_modules/cacache/locales/en.js
- /home/hector/ipn/distributions/node_modules/cacache/index.js
- /home/hector/ipn/distributions/node_modules/terser-webpack-plugin/dist/TaskRunner.js
- /home/hector/ipn/distributions/node_modules/terser-webpack-plugin/dist/index.js
- /home/hector/ipn/distributions/node_modules/terser-webpack-plugin/dist/cjs.js
- /home/hector/ipn/distributions/node_modules/webpack/lib/WebpackOptionsDefaulter.js
- /home/hector/ipn/distributions/node_modules/webpack/lib/webpack.js
- /home/hector/ipn/distributions/node_modules/webpack-cli/bin/utils/validate-options.js
- /home/hector/ipn/distributions/node_modules/webpack-cli/bin/utils/convert-argv.js
- /home/hector/ipn/distributions/node_modules/webpack-cli/bin/cli.js
- /home/hector/ipn/distributions/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
    at Function.Module._load (node:internal/modules/cjs/loader:774:27)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (/home/hector/ipn/distributions/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/hector/ipn/distributions/node_modules/readable-stream/lib/_stream_readable.js:40:18)
    at Module._compile (/home/hector/ipn/distributions/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (/home/hector/ipn/distributions/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/hector/ipn/distributions/node_modules/readable-stream/readable.js:6:28)
    at Module._compile (/home/hector/ipn/distributions/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (/home/hector/ipn/distributions/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/hector/ipn/distributions/node_modules/duplexify/index.js:1:76)
    at Module._compile (/home/hector/ipn/distributions/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (/home/hector/ipn/distributions/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/hector/ipn/distributions/node_modules/pumpify/index.js:3:17)
    at Module._compile (/home/hector/ipn/distributions/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (/home/hector/ipn/distributions/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/hector/ipn/distributions/node_modules/mississippi/index.js:3:27)
    at Module._compile (/home/hector/ipn/distributions/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/hector/ipn/distributions/node_modules/readable-stream/lib/_stream_readable.js',
    '/home/hector/ipn/distributions/node_modules/readable-stream/readable.js',
    '/home/hector/ipn/distributions/node_modules/duplexify/index.js',
    '/home/hector/ipn/distributions/node_modules/pumpify/index.js',
    '/home/hector/ipn/distributions/node_modules/mississippi/index.js',
    '/home/hector/ipn/distributions/node_modules/cacache/lib/entry-index.js',
    '/home/hector/ipn/distributions/node_modules/cacache/ls.js',
    '/home/hector/ipn/distributions/node_modules/cacache/locales/en.js',
    '/home/hector/ipn/distributions/node_modules/cacache/index.js',
    '/home/hector/ipn/distributions/node_modules/terser-webpack-plugin/dist/TaskRunner.js',
    '/home/hector/ipn/distributions/node_modules/terser-webpack-plugin/dist/index.js',
    '/home/hector/ipn/distributions/node_modules/terser-webpack-plugin/dist/cjs.js',
    '/home/hector/ipn/distributions/node_modules/webpack/lib/WebpackOptionsDefaulter.js',
    '/home/hector/ipn/distributions/node_modules/webpack/lib/webpack.js',
    '/home/hector/ipn/distributions/node_modules/webpack-cli/bin/utils/validate-options.js',
    '/home/hector/ipn/distributions/node_modules/webpack-cli/bin/utils/convert-argv.js',
    '/home/hector/ipn/distributions/node_modules/webpack-cli/bin/cli.js',
    '/home/hector/ipn/distributions/node_modules/webpack/bin/webpack.js'
  ]
}
```
Needed manual `npm install buffer-shims`. But otherwise worked, I think.

**Comment by Stebalien** [comment]
Ok... no idea. I don't even have that on my machine.

**Comment by olizilla** [comment]
I will take a look

**Comment by aschmahmann** [comment]
@olizilla note that I recently built and deployed with the latest version of Node and NPM and documented that in the README. I'm thinking we should be in agreement on what versions we're building with and updating the README if we build with newer versions than what's in the README to minimize discrepancies between builds

**Comment by aschmahmann** [comment]
Should be fixed by #352
